name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ultragrav
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy
        run: mvn --batch-mode package deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}